<?php
/**
 * @file
 * Implements 'desirable fields' functionality.
 * 
 * Allows administrators to set fields in user profiles that are
 * considered 'desirable.' Said fields are not required for registration but are
 * expected to be present on a profile within a certain time. The module
 * provides a list of users who have not filled in one or more desirable fields.
 */

/**
 * Implements hook_permission().
 */
function desirable_fields_permission() {
  $permissions = array();
  $permissions['administer desirable fields'] = array(
    'title' => t('Administer desirable fields'),
    'description' => t('Select which user profile fields are considered desirable.'),
    'restrict access' => TRUE,
  );
  $permissions['view user desirable fields status'] = array(
    'title' => t("View users' desirable fields status"),
    'description' => t("View a list of users who are missing one or more desirable fields on their profile."),
  );
  return $permissions;
}

/**
 * Implements hook_menu().
 */
function desirable_fields_menu() {
  $items = array();
  
  // Create main menu item and set callback to 'desirable_fields_define' form.
  $items['admin/config/people/accounts/desirable-fields'] = array(
    'title' => 'Desirable fields',
    'description' => 'Configure which fields are considered desirable and how they should be handled.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('desirable_fields_define'),
    'access arguments' => array('administer desirable fields'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  // Make a default tab to encompass the above.
  $items['admin/config/people/accounts/desirable-fields/settings'] = array(
    'title' => 'Set desirable fields',
    'description' => 'Configure which fields are considered desirable',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  // Make a new tab for listing user status regarding desirable fields.
  $items['admin/config/people/accounts/desirable-fields/user-status'] = array(
    'title' => "View users' field status",
    'description' => 'See which users do not have desired fields set',
    'page callback' => 'desirable_fields_list',
    'access arguments' => array('view user desirable fields status'),
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Administration form for defining which fields are desirable.
 */
function desirable_fields_define() {
  $form = array();
  
  $form['desirable_fields_selected_fields'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Desirable fields'),
    '#description' => t('Fields selected here are marked as desirable.'),
    '#options' => _desirable_fields_list_all_fields(),
    '#default_value' => variable_get('desirable_fields_selected_fields', array()),
  );
  
  return system_settings_form($form);
}

/**
 * Administration list of users who haven't filled in desired fields.
 */
function desirable_fields_list() {
  $list_users = desirable_fields_list_users_missing_fields();

  $header = array('User', 'Fields not filled', 'Signup date');
  $rows = array();
  
  foreach ($list_users as $user) {
    $missing_fields_name = array();
    foreach ($user['missing_fields'] as $missing_field) {
      array_push($missing_fields_name, field_info_instance('user', $missing_field, 'user')['label']);
    }
    
    array_push($rows, array(
      l($user['name'], $user['profile_link']),
      theme('item_list', array(
        'items' => $missing_fields_name,
      )),
      format_date($user['created'], 'short'),
      )
    );
  }
  
  $list = array(
    '#markup' => '<p>The following table shows which users have not filled in the desired fields.</p>'
    . theme(
      'table', array(
        'header' => $header,
        'rows' => $rows,
      )
    ),
  );
  
  return $list;
}

/**
 * Returns the list of all available user fields.
 */
function _desirable_fields_list_all_fields() {
  $info = entity_get_property_info('user');
  $fields = array();
  
  foreach ($info['bundles']['user']['properties'] as $key => $field) {
    $fields[$key] = $field['label'];
  }
    
  return $fields;
}

/**
 * Returns all users who do not have desirable fields filled.
 * 
 * Returns an array of the following structure:
 * 
 * - {uid}
 *    - missing_fields
 *      - {field name}
 *      - {field name}
 *      - ...
 *    - name => {username}
 *    - profile_link => {relative user path}
 * - ...
 */
function desirable_fields_list_users_missing_fields() {
  $desirable_fields = variable_get('desirable_fields_selected_fields');
  
  // Remove unselected fields entirely.
  foreach ($desirable_fields as $key => $field) {
    if ($field == '0') {
      unset($desirable_fields[$key]);
    }
  }
  
  // As a side note, in Drupal 8 it's entity_load_multiple().
  $users = entity_load('user');
  // Ignore anonymous user.
  unset($users[0]);
    
  $users_missing_fields = array();
  
  foreach ($users as $user) {
    $users_missing_fields[$user->uid] = array();
    $users_missing_fields[$user->uid]['missing_fields'] = array();
    foreach ($desirable_fields as $field_key => $field) {
      if (empty($user->$field_key)) {
        array_push($users_missing_fields[$user->uid]['missing_fields'], $field);
      }
    }
    // Remove users with no missing fields now that users are processed.
    if (empty($users_missing_fields[$user->uid]['missing_fields'])) {
      unset($users_missing_fields[$user->uid]);
    }
    else {
      $users_missing_fields[$user->uid]['name'] = $user->name;
      $users_missing_fields[$user->uid]['profile_link'] = drupal_get_path_alias('user/' . $user->uid);
      $users_missing_fields[$user->uid]['created'] = $user->created;
    }
  }
  
  return $users_missing_fields;
  
}
